project:
  type: website
  resources:
    - "google0b1c69839077c1a0.html"

website:
  title: "Anouck Butraud-Assathian"
  site-url: "https://AnouckAnouck.github.io"
  description: "PhD candidate in Economics specializing in cultural and digital economics at Centre d'Économie de la Sorbonne and PcEn Chair."
  navbar:
    left:
      - href: research.qmd
        text: Research
      - href: communications.qmd
        text: Communications
      - href: Teaching.qmd
        text: Teaching

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

publish:
  output-dir: _site